### ISSUE TITLE
Suggestion: Add Blue Color Option to Obsidian Sunset Theme

### ISSUE THREAD

**Issue by hudy0** [lczerniawski/ObsidianSunset-JetBrains#1]
Hi lczerniawski,

First, I want to say how much I appreciate the `Obsidian Sunset Theme` theme. The orange color scheme is vibrant and suits my needs really well. 

I have a suggestion that I believe could enhance the theme even further. Would it be possible to add a blue color option as an alternative? I’ve noticed that the native `PyCharm` dark theme uses blue for buttons and other elements, which provides a nice contrast and complements the overall dark theme effectively. Incorporating a similar blue option could offer users additional customization choices and improve the versatility of the theme.
you can let the user choose between orange or other colour 

If you think this is a feasible idea, I’d be happy to assist with testing or provide feedback on any implementations.

Thank you for considering this suggestion and for all your hard work on the theme!

Best regards,

**Comment by lczerniawski** [comment]
Hi @hudy0,
It's great to hear that you like it, it's much appreciated!

I hadn't thought of adding any other colours before, but if you find that useful, I will be happy to add it.
As it is your suggestion, do you want to choose the colour for the accent to suit your taste?

**Comment by hudy0** [comment]
Hi @lczerniawski 

Yes it's gone be a great idea switching between different colours 
Buttons can be blue or orange 
Someone can switch between colours they like

**Comment by lczerniawski** [comment]
@hudy0 I just pushed version 2.0, which contains a blue colour accent, let me know how you like it.

**Comment by hudy0** [comment]
@lczerniawski  Hey, I just updated to V2. It looks great so far!

**Comment by hudy0** [comment]
Keep this issue open for any future feedback ☘️
